config/routes.rb
Rails.application.routes.draw do

  resources :borrow_histories
  # so that only authenticated user can access these pages.
  # Refer: https://github.com/plataformatec/devise/wiki/How-To:-Require-authentication-for-all-pages
  # and https://github.com/plataformatec/devise/wiki/How-To:-Define-resource-actions-that-require-authentication-using-routes.rb
  authenticate :user do
    # root 'test_home_page#index'
    get 'homepage', to: 'test_home_page#index', as: 'user_homepage'
    get 'home/index'
    resources :admins
    resources :librarians
    resources :students
    resources :books
    resources :libraries
    resources :bookmarks

    get 'book/show'
    get 'book/edit'
    get 'book/destroy'
    get 'book/create'
    get 'book/new'
    get 'urls/new'
  end

  root 'home#index'
  get 'page2', to: 'page2#index', as: 'page2'
  get 'book_request', to: 'books#book_request', as: 'book_request'

  # get 'borrow_history', to: 'borrow_histories#'

  get 'bookmarked', to: 'books#bookmarked', as: 'bookmarked'
  get 'unbookmarked', to: 'bookmarks#unbookmark', as: 'unbookmarked'
  get 'list_special_book_request', to: 'librarians#list_special_book_request', as: 'list_special_book_request'
  get 'approve_book_request', to: 'librarians#approve_book_request', as: 'approve_book_request'
  get 'approve_librarian', to: 'admins#approve_librarian', as: 'approve_librarian'
  get 'librarian_requests', to: 'admins#librarian_requests', as: 'librarian_requests'
  get 'requests', to: 'book_requests#index', as: 'requests'
  get 'returns', to: 'book_requests#returns', as: 'returns'
  get 'hold_requests', to: 'book_requests#hold_requests', as: 'hold_requests'
  get 'delete_hold_request', to: 'book_requests#delete_hold_request', as: 'delete_hold_request'
  # devise_for :users, :controllers => { registrations: 'registrations'}

  get 'fb_details_new', to: 'ask_details_fb_login#new', as: 'fb_details_new'
  get 'fb_details_create', to: 'ask_details_fb_login#create', as: 'fb_details_create'

  devise_for :users, :controllers => { registrations: 'registrations', omniauth_callbacks: 'users/omniauth_callbacks'}




  # devise_scope :user do
  #   # to change the page displayed after sign in. Refer: https://stackoverflow.com/a/25243422/6543250
  #   get 'user_root', :to => 'registrations#after_sign_in_path_for'
  # end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/Bookmark.rb
class Bookmark < ApplicationRecord
end

app/models/admin.rb
class Admin < ApplicationRecord
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image

  validates :isbn , :presence => true, :uniqueness => true, format: { with: /[0-9]+/, message: 'Only numbers allowed.'}
  validates :title, :presence => true
  validates :author, :presence => true
  validates :edition, format: { with: /[0-9]*/, message: 'Only numbers allowed.' }
  validates :book_count, presence: true

end

app/models/book_request.rb
class BookRequest < ApplicationRecord
  self.table_name='book_request'
  belongs_to :books
  belongs_to :librarians
  belongs_to :students

end

app/models/borrow_history.rb
class BorrowHistory < ApplicationRecord

end

app/models/librarian.rb
class Librarian < ApplicationRecord
  # belongs_to :library, :foreign_key => "libraries_id"
  # delegate :libraries_id, :to => :library
end

app/models/library.rb
class Library < ApplicationRecord
  # has_many :librarians
end

app/models/student.rb
class Student < ApplicationRecord

end

app/models/user.rb
class User < ApplicationRecord
  enum role: {user: 0, librarian: 1, admin: 2}
  after_initialize :set_default_role,:if => :new_record?
  # before_save :copy_data
  # after_save :copy_data

  has_many :students
  has_many :librarians
  accepts_nested_attributes_for :students
  accepts_nested_attributes_for :librarians

  def set_default_role
    self.role ||= :user
  end

  def copy_data
    if self.librarian?
      # if not @user = Librarian.find(self.id)
      @user = User.find(self.id)
      if Librarian.find_by_email(self.email).nil?
        @lib = Librarian.new(email: self.email, password: self.encrypted_password, libraries_id: 1)
        @lib.save
        #   flash[:success] = "Successfully saved data to Librarian model"
        # redirect_to librarians_path

        # else
        #   flash[:error] = "Could not create record"
        # end
      end

        # @user = Librarian.find(self.id)
        # if (nil == @user)
        #   @lib = Librarian.create(email: self.email, name:self.email, password: self.encrypted_password, users_id: self.id)
        #   @lib.save
        # else
        #   @lib = Librarian.create(email: self.email, name:self.email, password: self.encrypted_password, users_id: self.id)
        #   @lib.save
        # end
      #
    elsif self.user?
      # @user = User.find(self.id)
      if Student.find_by_email(self.email).nil?
        @stud = Student.new(email: self.email, password: self.encrypted_password)
        @stud.save
        #   flash[:success] = "Successfully saved data to Student model"
        # redirect_to students_path
        # else
        #   flash[:error] = "Could not create record"
        # end
      end
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      # user.name = auth.info.name   # assuming the user model has a name
      # user.image = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  devise :omniauthable, omniauth_providers: %i[facebook]

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/library_helper.rb
module LibraryHelper
end

app/helpers/page2_helper.rb
module Page2Helper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admins/_form.html.erb
<%= form_with(model: admin, local: true) do |form| %>
  <% if admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
      <% admin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, :id=>'admin_email' %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

<!--  <div class="field">-->
    <%#= form.label :password %>
    <%#= form.text_field :password %>
<!--  </div>-->

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admins/edit.html.erb
<h1>Editing Admin</h1>

<%= render 'form', admin: @admin %>

<%= link_to 'Show', @admin %> |
<%= link_to 'Back', admins_path %>

app/views/admins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Admins</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admins.each do |admin| %>
      <tr>
        <td><%= admin.email %></td>
<!--        <td><%#= admin.name %></td>-->
        <td><%= admin.password %></td>
<!--        <td><%#= link_to 'Approve', admin %></td>-->
        <td><%= link_to 'Edit', edit_admin_path(admin) %></td>

<!--        <td><%#= link_to 'Destroy', admin, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Admin', new_admin_path %>
<%#= link_to 'Approve', librarian_requests_path %>

app/views/admins/librarian_requests.html.erb
<h1>Approve Librarians</h1>

<p id="notice"><%= notice %></p>

<table>
  <thead>
  <tr>
    <th>Email</th>
    <th>Name</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>

  <% @lib.each do |librarian| %>
    <tr>
      <td><%= librarian.email %></td>
      <td><%= librarian.name %></td>
      <td><%= link_to 'Approve', approve_librarian_path(librarian) %></td>
      <td><%= link_to 'Destroy', librarian, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>


  </tbody>

</table>
<br><%= link_to 'Back', home_index_path %> |

app/views/admins/new.html.erb
<h1>New Admin</h1>

<%= render 'form', admin: @admin %>

<%= link_to 'Back', admins_path %>

app/views/admins/show.html.erb
<p id="notice"><%= notice %></p>
<h2> Your Profile </h2>
<p>
  <strong>Email:</strong>
  <%= @admin.email %>
</p>

<p>
  <strong>Name:</strong>
  <%= @admin.name %>
</p>

<!--<p>-->
<!--  <strong>Password:</strong>-->
  <%#= @admin.password %>
<!--</p>-->

<%= link_to 'Edit Profile', edit_admin_path(@admin) %> <br>
<br><%= link_to 'Back', home_index_path %> |

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Library Management System</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application.css', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application.js', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="alert"><%= alert %></p>


    <%= yield %>
    <% if user_signed_in? %>
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
    <% end %>
    </body>
</html>