config/routes.rb
Rails.application.routes.draw do

  resources :borrow_histories
  # so that only authenticated user can access these pages.
  # Refer: https://github.com/plataformatec/devise/wiki/How-To:-Require-authentication-for-all-pages
  # and https://github.com/plataformatec/devise/wiki/How-To:-Define-resource-actions-that-require-authentication-using-routes.rb
  authenticate :user do
    # root 'test_home_page#index'
    get 'homepage', to: 'test_home_page#index', as: 'user_homepage'
    get 'home/index'
    resources :admins
    resources :librarians
    resources :students
    resources :books
    resources :libraries
    resources :bookmarks

    get 'book/show'
    get 'book/edit'
    get 'book/destroy'
    get 'book/create'
    get 'book/new'
    get 'urls/new'
  end

  root 'home#index'
  get 'page2', to: 'page2#index', as: 'page2'
  get 'book_request', to: 'books#book_request', as: 'book_request'

  # get 'borrow_history', to: 'borrow_histories#'

  get 'bookmarked', to: 'books#bookmarked', as: 'bookmarked'
  get 'unbookmarked', to: 'bookmarks#unbookmark', as: 'unbookmarked'
  get 'list_special_book_request', to: 'librarians#list_special_book_request', as: 'list_special_book_request'
  get 'approve_book_request', to: 'librarians#approve_book_request', as: 'approve_book_request'
  get 'approve_librarian', to: 'admins#approve_librarian', as: 'approve_librarian'
  get 'librarian_requests', to: 'admins#librarian_requests', as: 'librarian_requests'
  get 'requests', to: 'book_requests#index', as: 'requests'
  get 'returns', to: 'book_requests#returns', as: 'returns'
  get 'hold_requests', to: 'book_requests#hold_requests', as: 'hold_requests'
  get 'delete_hold_request', to: 'book_requests#delete_hold_request', as: 'delete_hold_request'
  # devise_for :users, :controllers => { registrations: 'registrations'}

  get 'fb_details_new', to: 'ask_details_fb_login#new', as: 'fb_details_new'
  get 'fb_details_create', to: 'ask_details_fb_login#create', as: 'fb_details_create'

  devise_for :users, :controllers => { registrations: 'registrations', omniauth_callbacks: 'users/omniauth_callbacks'}




  # devise_scope :user do
  #   # to change the page displayed after sign in. Refer: https://stackoverflow.com/a/25243422/6543250
  #   get 'user_root', :to => 'registrations#after_sign_in_path_for'
  # end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/student.rb
class Student < ApplicationRecord

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]
  after_action :verify_authorized
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # GET /students
  # GET /students.json
  def index
    authorize Student
    if User.find_by_email(current_user.email).provider == 'facebook' and Student.find_by_email(current_user.email).education == 'DUMMY'
      redirect_to edit_student_path(Student.find_by_email(current_user.email)), notice: 'Please fill out details first !'
    end

    @students = Student.all
    # authorize Student
  end

  # GET /students/1
  # GET /students/1.json
  def show
    authorize Student
    if(current_user.user?)
      @stud = Student.find_by_email(current_user.email)
      @stud2 = Student.find(params[:id])
      if(@stud.id!=@stud2[:id])
        flash[:alert] = "You are not authorized to perform this action."
        redirect_to(request.referrer || root_path)
      end
    end
  end

  # GET /students/new
  def new
    @student = Student.new
    authorize Student
  end

  # GET /students/1/edit
  def edit
    authorize Student
    if(current_user.user?)
      @stud = Student.find_by_email(current_user.email)
      @stud2 = Student.find(params[:id])
      if(@stud.id!=@stud2[:id])
        flash[:alert] = "You are not authorized to perform this action."
        redirect_to(request.referrer || root_path)
      end
    end
  end

  # POST /students
  # POST /students.json
  def create
    authorize Student
    student_params[:fines]=0
    @student = Student.new(student_params)
    @user = User.new({email:@student.email,password:@student.password,password_confirmation:@student.password})
    respond_to do |format|
      if @student.save
        if(@student[:education]=="Masters")
          @student.update({max_books:4})
        elsif (@student[:education]=="PhD")
           @student.update({max_books:6})
        else
          @student.update({max_books:2})
        end
        @user.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    authorize Student
    @user = User.find_by_email(@student.email)
    # if student_params['education'] == 'Undergraduate'
    #   student_params[:student][:max_books] = 2
    # elsif student_params['education'] == 'Masters'
    #   student_params[:student][:max_books] = 4
    # else
    #   student_params[:student][:max_books] = 6
    # end

    respond_to do |format|
      if @student.update(student_params)
        @user.update({email:@student.email})

        maxbooks_cnt=0
        # update max_books here
        education = @student.education
        if education == 'Undergraduate'
          maxbooks_cnt = 2
        elsif education == 'Masters'
          maxbooks_cnt = 4
        else
          maxbooks_cnt = 6
        end

        # fire update query here
        @student.update(max_books: maxbooks_cnt)

        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    authorize Student
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def find_student_id(email)
    return Student.find_by_email(email)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:email, :name, :password, :education, :university, :max_books, :fines)
    end

    def user_not_authorized
      flash[:alert] = "You are not authorized to perform this action."
      redirect_to(request.referrer || root_path)
    end
end

app/helpers/student_helper.rb
module StudentHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_edit_form.html.erb
<%= form_with(model: student, local: true) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <% if User.find_by_email(student.email).provider == 'facebook' %>
      <%= form.text_field :email, :required => true, :disabled => true %>
    <% else %>
      <%= form.text_field :email, :required => true %>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, :required => true %>
  </div>

  <div class=""field>
    <% if User.find_by_email(student.email).provider == 'facebook' and student.education=='DUMMY' %>
      <%# if student.education == "" || student.education.nil? %>
        <%= form.label :education %>
        <%= form.select :education, options_for_select([ ["Undergraduate","Undergradudate"], ["Masters","Masters"], ["PhD", "PhD"] ]), :required => true %>
      <%# end %>
    <% else %>
      <% if student.education == "" || student.education.nil? %>
        <%= form.label :education %>
        <%= form.select :education, options_for_select([ ["Undergraduate","Undergradudate"], ["Masters","Masters"], ["PhD", "PhD"] ]), :required => true %>
      <% end %>
    <% end %>
  </div>


  <%# if student.education == "" || student.education.nil? %>
<!--    <div class="field">-->
      <%#= form.label :education %>
      <%#= form.select :education, options_for_select([ ["Undergraduate","Undergradudate"], ["Masters","Masters"], ["PhD", "PhD"] ]), :required => true %>
<!--    </div>-->
  <%# end %>

  <div class="field">
    <% if User.find_by_email(student.email).provider == 'facebook' and student.university=='DUMMY' %>
      <%= form.label :university %>
      <%= form.text_field :university, :required => true %>
    <% else %>
      <%= form.label :university %>
      <%= form.text_field :university, :required => true, :disabled => !(student.university == "" || student.university.nil?) %>
    <% end %>

    <%#= form.label User.find_by_email(student.email).provider %>
    <%#= form.label :university %>
    <%#= form.text_field :university, :required => true, :disabled => !(student.university == "" || student.university.nil?) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/students/_form.html.erb
<%= form_with(model: student, local: true) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, :required => true %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, :required => true %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password , :required => true%>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, :required => true %>
  </div>

  <div>
    <span id="student_message"></span>
  </div>

  <% if student.education == "" || student.education.nil? %>
    <div class="field">
      <%= form.label :education %>
      <%= form.select :education, options_for_select([ ["Undergraduate","Undergradudate"], ["Masters","Masters"], ["PhD", "PhD"] ]), :required => true  %>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :university %>
    <%= form.text_field :university, :required => true, :disabled => !(student.university == "" || student.university.nil?) %>
  </div>

  <div class="field" id="mb_field">
    <%= form.label :max_books %>
    <%= form.number_field :max_books %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'edit_form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<!--<h1>Welcome <%#= Student %>></h1>-->

<% if current_user.user? %>
  <h1>Welcome <%= Student.find_by_email(current_user.email).name %> !</h1>
<% else %>
  <h1>Students</h1>
<% end %>

<table>
  <thead>
    <% if current_user.admin? %>
      <tr>
        <th>Email</th>
        <th>Name</th>
        <th>Education</th>
        <th>University</th>
        <th>Max books</th>
        <th colspan="3"></th>
      </tr>
    <% end %>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <% if current_user.admin? %>
      <tr>
        <td><%= student.email %></td>
        <td><%= student.name %></td>
        <td><%= student.education %></td>
        <td><%= student.university %></td>
        <td><%= student.max_books %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <% if current_user.admin? %>
          <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>



<!--      Display student info here - NOT REQUIRED-->
      <%# elsif current_user.user? && ((current_user.email == student.email) )%>
<!--      <tr>-->
<!--        <td><%#= student.email %></td>-->
<!--        <td><%#= student.name %></td>-->
<!--        <td><%#= student.education %></td>-->
<!--        <td><%#= student.university %></td>-->
<!--        <td><%#= student.max_books %></td>-->
<!--        <td><%#= link_to 'Show', student %></td>-->
<!--        <td><%#= link_to 'Edit', edit_student_path(student) %></td>-->
<!--      </tr>-->




      <%end %>
    <% end %>
  </tbody>
</table>
<br>

<% if current_user.admin? %>
  <%= link_to 'New Student', new_student_path %><br>
<% end %>

<!-- ## For user specific options to be displayed ## -->
<%# if current_user.user? %>
<!--  <%#= link_to 'View Bookmarks', dummy_path1 %><br>-->
<!--  <%#= link_to 'View Currently Issued books', dummy_path2 %><br>-->
<!--  <%#= link_to 'View Fine History', dummy_path3 %><br>-->
<%# end %>

<%= link_to 'View Libraries',  libraries_path %><br>
<%= link_to 'View Books', books_path %><br>
<%= link_to 'View All Requested Books', requests_path %><br>
<%= link_to 'View Hold/Pending Approval Requests', hold_requests_path %><br>
<%= link_to 'View Bookmarked Books', bookmarks_path %><br>

<% if current_user.user? %>
  <br><%= link_to 'My Profile', Student.find_by_email(current_user.email) %><br>
<% end %>

<% unless current_user.user? %>
  <br><%= link_to 'Back', user_homepage_path %><br>
<% end %>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<h2>Student Profile:</h2><br>


<p>
  <strong>Email:</strong>
  <%= @student.email %>
</p>

<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>

<!--<p>-->
<!--  <strong>Password:</strong>-->
  <%#= @student.password %>
<!--</p>-->

<p>
  <strong>Education:</strong>
  <%= @student.education %>
</p>

<p>
  <strong>University:</strong>
  <%= @student.university %>
</p>

<p>
  <strong>Max books:</strong>
  <%= @student.max_books %>
</p>

<p>
  <strong>Fines:</strong>
  <%= @student.fines %>
</p>

<br><%= link_to 'Change Password', edit_user_registration_path %><br>
<%= link_to 'Edit Profile', edit_student_path(@student) %><br>
<br><%= link_to 'Back', students_path %> |