config/routes.rb
Rails.application.routes.draw do

  resources :borrow_histories
  # so that only authenticated user can access these pages.
  # Refer: https://github.com/plataformatec/devise/wiki/How-To:-Require-authentication-for-all-pages
  # and https://github.com/plataformatec/devise/wiki/How-To:-Define-resource-actions-that-require-authentication-using-routes.rb
  authenticate :user do
    # root 'test_home_page#index'
    get 'homepage', to: 'test_home_page#index', as: 'user_homepage'
    get 'home/index'
    resources :admins
    resources :librarians
    resources :students
    resources :books
    resources :libraries
    resources :bookmarks

    get 'book/show'
    get 'book/edit'
    get 'book/destroy'
    get 'book/create'
    get 'book/new'
    get 'urls/new'
  end

  root 'home#index'
  get 'page2', to: 'page2#index', as: 'page2'
  get 'book_request', to: 'books#book_request', as: 'book_request'

  # get 'borrow_history', to: 'borrow_histories#'

  get 'bookmarked', to: 'books#bookmarked', as: 'bookmarked'
  get 'unbookmarked', to: 'bookmarks#unbookmark', as: 'unbookmarked'
  get 'list_special_book_request', to: 'librarians#list_special_book_request', as: 'list_special_book_request'
  get 'approve_book_request', to: 'librarians#approve_book_request', as: 'approve_book_request'
  get 'approve_librarian', to: 'admins#approve_librarian', as: 'approve_librarian'
  get 'librarian_requests', to: 'admins#librarian_requests', as: 'librarian_requests'
  get 'requests', to: 'book_requests#index', as: 'requests'
  get 'returns', to: 'book_requests#returns', as: 'returns'
  get 'hold_requests', to: 'book_requests#hold_requests', as: 'hold_requests'
  get 'delete_hold_request', to: 'book_requests#delete_hold_request', as: 'delete_hold_request'
  # devise_for :users, :controllers => { registrations: 'registrations'}

  get 'fb_details_new', to: 'ask_details_fb_login#new', as: 'fb_details_new'
  get 'fb_details_create', to: 'ask_details_fb_login#create', as: 'fb_details_create'

  devise_for :users, :controllers => { registrations: 'registrations', omniauth_callbacks: 'users/omniauth_callbacks'}




  # devise_scope :user do
  #   # to change the page displayed after sign in. Refer: https://stackoverflow.com/a/25243422/6543250
  #   get 'user_root', :to => 'registrations#after_sign_in_path_for'
  # end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/book_request.rb
class BookRequest < ApplicationRecord
  self.table_name='book_request'
  belongs_to :books
  belongs_to :librarians
  belongs_to :students

end

app/controllers/book_requests_controller.rb
class BookRequestsController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  def index
    # @br = BookRequest.all
    @br = BookRequest.all.where(hold: false)
    @book_dict = {}
    @books = Book.all

    @student_dict = {}
    @stud_fines={}
    @individual_fines={}
    @students = Student.all
    @books.each do |book|
      @book_dict[book.id] = book.title
    end
    @students.each do |student|
      @stud_fines[student.id]=0
      @student_dict[student.id]=student.email
    end


    @br.each do |request|
      @book = Book.find(request[:books_id])
      @libr = Library.find(@book[:libraries_id])
      @get_rate = @libr[:fines]
      # @stud_fines[:]
      # @stud =
      # calculate the fine of each book.
      @late_by = (Date.today.mjd-(request[:date].mjd+@libr[:max_days]))
      if(@late_by>0)
        @fined = @late_by*@get_rate
      else
        @fined = 0
      end
      @individual_fines[request.id] = @fined
      @stud_fines[request[:students_id]] += @fined
    end

    @students.each do |student|
      student.update(fines:@stud_fines[student.id])
    end

  end
  def show
    @book = Book.where(params[:id])
  end
  def create
  end
  def edit
  end
  def update
  end
  def destroy
    # @book_request.destroy
    # respond_to do |format|
    #   format.html { redirect_to requests_path, notice: 'Book was successfully returned.' }
    #   format.json { head :no_content }
    # end
  end
  def returns
    # @book = Book.find(params[:id])
    # @student = Student.find_by_email(current_user.email)
    # @book_request = BookRequest.find_by_sql(["select * from book_request where students_id = ? AND books_id = ?",@student.id,@book.id])
    @book_request = BookRequest.find(params[:id])
    @book = Book.find(@book_request[:books_id])
    @student = Student.find(@book_request[:students_id])
    @libr = Library.find(@book[:libraries_id])
    @get_rate = @libr[:fines]
    if @book_request.nil?

    else
      @late_by = (Date.today.mjd-(@book_request[:date].mjd+@libr[:max_days]))
      if(@late_by>0)
        @fined = @late_by*@get_rate
      else
        @fined = 0
      end
        @stud_fines = @student[:fines] - @fined
        @student.update(fines:@stud_fines)
        @book_request.destroy
        @book.update_attribute(:available_count, @book[:available_count]+1)
        @borrow_history = BorrowHistory.new(:date => Date.today, :is_special => @book.special_collection, :books_id => @book.id, :students_id => @student.id, :status => "Returned")
        @borrow_history.save
        @book_hold_req = BookRequest.find_by_sql(["select * from book_request where books_id = ? and hold = ?",@book.id,true])


        if !(@book_hold_req[0].nil?)
          if(@book_hold_req[0][:is_special] == true)
            @book_hold_req[0].update_attribute(:hold, "false")
            @book.update_attribute(:available_count, @book[:available_count]-1)
            redirect_to(root_path, notice: @book_hold_req[0][:books_id].to_s+" has been issued to other user, approval request sent to librarian") and return
          else
            @book_hold_req[0].update_attribute(:hold, "true")
            @book_hold_req[0].update_attribute(:is_approved, "true")
            @book.update_attribute(:available_count, @book[:available_count]-1)

            @student_1 = Student.find(@book_hold_req[0][:student_id])
            @borrow_history = BorrowHistory.new(:date => Date.today, :is_special => @book.special_collection, :books_id => @book.id, :students_id => @student.id, :status => "Checked Out")
            @borrow_history.save

            redirect_to(root_path, notice: @book_hold_req[0][:books_id].to_s+" has been issued to other user") and return


          end
        end
        respond_to do |format|
          format.html { redirect_to requests_path, notice: 'Book was successfully returned.' }
          format.json { head :no_content }




      end

  end
  end

  def hold_requests
    @student = Student.find_by_email(current_user.email)
    @book_request = BookRequest.find_by_sql(["select * from book_request where students_id = ? and hold = ?",@student.id,true])
    @book_request_1 = BookRequest.find_by_sql(["select * from book_request where students_id = ? and is_approved = ? and hold = ?",@student.id,false,false])

  end

  def delete_hold_request
    @book_request = BookRequest.find(params[:id])
    if(@book_request.hold==false)
      @book = Book.find(@book_request[:books_id])
      @book.update({available_count:@book[:available_count]+1})
    end
    @book_request.delete
  end

end

app/views/book_requests/delete_hold_request.html.erb
<script type="text/javascript">
    window.location.href="hold_requests"
</script>

app/views/book_requests/hold_requests.html.erb
<p5><b>Books on Hold Requests</b></p5>
<table>
  <thead>
  <tr>
    <th>ID</th>
    <th>Book ID</th>
    <th>Book Title</th>
  </tr>

  </thead>

  <tbody>
  <% @book_request.each do |book_request| %>
    <% @book_title = Book.find(book_request[:books_id]).title %>
    <tr>
      <td><%= book_request[:id] %></td>
      <td><%= book_request[:books_id] %></td>
      <td><%= @book_title %></td>
      <td><%= link_to 'Delete Reservation/Hold Request', delete_hold_request_path(:id => book_request[:id])  %></td>
    </tr>
  <% end %>
  </tbody>

</table><br><br><br>

<p5><b>Books pending Approval from Librarian</b></p5>

<table>
  <thead>
  <tr>
    <th>ID</th>
    <th>Book ID</th>
    <th>Book Title</th>
  </tr>

  </thead>

  <tbody>
  <% @book_request_1.each do |book_request_1| %>
    <% @book_title_1 = Book.find(book_request_1[:books_id]).title %>
    <tr>
      <td><%= book_request_1[:id] %></td>
      <td><%= book_request_1[:books_id] %></td>
      <td><%= @book_title_1 %></td>
      <td><%= link_to 'Cancel Pending Approval Book Request', delete_hold_request_path(:id => book_request_1[:id])  %></td>
    </tr>
  <% end %>
  </tbody>

</table>


<br><%= link_to 'Back', home_index_path %>

app/views/book_requests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books Requested</h1>

<table>
  <thead>
  <tr>
    <th>Date</th>
    <th>Book Name</th>
    <th>Special</th>
    <th>Approved</th>
    <th>Library</th>
    <th>Fines</th>
    <% if current_user.librarian? %>
      <th>Student Name</th>
      <th>Student Email</th>
    <% end %>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @br.each do |request| %>
    <% @id = request[:students_id] %>
    <% @current_email = current_user.email %>
    <% @email = @student_dict[@id]%>
    <% @book = Book.find(request[:books_id]) %>
    <% @book_lib = @book[:libraries_id] %>
    <% if current_user.user? %>
      <% if @email==@current_email %>
      <tr>
        <td><%= request.date %></td>
        <td><%= @book_dict[request[:books_id]] %></td>
        <td><%= request.is_special %></td>
        <td><%= request.is_approved %></td>
        <td><%= Library.find(@book_lib).name %></td>
        <td><%= @individual_fines[request[:id]] %></td>
        <td><%= link_to 'Show', book_path(request[:books_id]) %></td>
<!--        <td><%#= link_to 'Destroy', request, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
        <% if request.is_approved %>
        <td><%= link_to 'Return', returns_path(:id => request[:id]) %></td>
<!--          <td><%#= link_to 'Return', request, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
       <% end %>
      </tr>
  <% end %>
    <% else if current_user.librarian? %>
      <% @lib = Librarian.find_by_email(current_user.email) %>
        <% @lib_id = @lib[:libraries_id] %>
        <% @book = Book.find(request[:books_id]) %>
        <% @book_lib = @book[:libraries_id] %>
        <% if @lib_id == @book_lib %>
        <tr>
          <td><%= request.date %></td>
          <td><%= @book_dict[request[:books_id]] %></td>
          <td><%= request.is_special %></td>
          <td><%= request.is_approved %></td>
          <td><%= Library.find(@book_lib).name %></td>
          <td><%= @individual_fines[request[:id]] %></td>
          <td><%= Student.find(request[:students_id]).name %></td>
          <td><%= Student.find(request[:students_id]).email %></td>
          <td><%= link_to 'Show Book', book_path(request[:books_id]) %></td>
          <td><%= link_to 'Show Student', student_path(request[:students_id]) %></td>
          <!--        <td><%#= link_to 'Destroy', request, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
          <%# if request.is_approved %>
<!--            <td><%#= link_to 'Return', returns_path(:id => request[:id]) %></td>-->
            <!--          <td><%#= link_to 'Return', request, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
          <%# end %>
        </tr>
        <% end %>
      <% else %>
        <% @book = Book.find(request[:books_id]) %>
        <% @book_lib = @book[:libraries_id] %>
        <tr>
            <td><%= request.date %></td>
            <td><%= @book_dict[request[:books_id]] %></td>
            <td><%= request.is_special %></td>
            <td><%= request.is_approved %></td>
            <td><%= Library.find(@book_lib).name %></td>
            <td><%= @individual_fines[request[:id]] %></td>
            <td><%= Student.find(request[:students_id]).name %></td>
            <td><%= Student.find(request[:students_id]).email %></td>
            <td><%= link_to 'Show Book', book_path(request[:books_id]) %></td>
            <td><%= link_to 'Show Student', student_path(request[:students_id]) %></td>
          </tr>
    <% end %>
  <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Show All Libraries',  libraries_path %>
<%= link_to 'View All Books', books_path %>
<%= link_to 'Back', :back %>

app/views/book_requests/returns.html.erb
<%= request[:books_id] %>
<%= params[:id] %>