config/routes.rb
Rails.application.routes.draw do

  resources :borrow_histories
  # so that only authenticated user can access these pages.
  # Refer: https://github.com/plataformatec/devise/wiki/How-To:-Require-authentication-for-all-pages
  # and https://github.com/plataformatec/devise/wiki/How-To:-Define-resource-actions-that-require-authentication-using-routes.rb
  authenticate :user do
    # root 'test_home_page#index'
    get 'homepage', to: 'test_home_page#index', as: 'user_homepage'
    get 'home/index'
    resources :admins
    resources :librarians
    resources :students
    resources :books
    resources :libraries
    resources :bookmarks

    get 'book/show'
    get 'book/edit'
    get 'book/destroy'
    get 'book/create'
    get 'book/new'
    get 'urls/new'
  end

  root 'home#index'
  get 'page2', to: 'page2#index', as: 'page2'
  get 'book_request', to: 'books#book_request', as: 'book_request'

  # get 'borrow_history', to: 'borrow_histories#'

  get 'bookmarked', to: 'books#bookmarked', as: 'bookmarked'
  get 'unbookmarked', to: 'bookmarks#unbookmark', as: 'unbookmarked'
  get 'list_special_book_request', to: 'librarians#list_special_book_request', as: 'list_special_book_request'
  get 'approve_book_request', to: 'librarians#approve_book_request', as: 'approve_book_request'
  get 'approve_librarian', to: 'admins#approve_librarian', as: 'approve_librarian'
  get 'librarian_requests', to: 'admins#librarian_requests', as: 'librarian_requests'
  get 'requests', to: 'book_requests#index', as: 'requests'
  get 'returns', to: 'book_requests#returns', as: 'returns'
  get 'hold_requests', to: 'book_requests#hold_requests', as: 'hold_requests'
  get 'delete_hold_request', to: 'book_requests#delete_hold_request', as: 'delete_hold_request'
  # devise_for :users, :controllers => { registrations: 'registrations'}

  get 'fb_details_new', to: 'ask_details_fb_login#new', as: 'fb_details_new'
  get 'fb_details_create', to: 'ask_details_fb_login#create', as: 'fb_details_create'

  devise_for :users, :controllers => { registrations: 'registrations', omniauth_callbacks: 'users/omniauth_callbacks'}




  # devise_scope :user do
  #   # to change the page displayed after sign in. Refer: https://stackoverflow.com/a/25243422/6543250
  #   get 'user_root', :to => 'registrations#after_sign_in_path_for'
  # end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/librarian.rb
class Librarian < ApplicationRecord
  # belongs_to :library, :foreign_key => "libraries_id"
  # delegate :libraries_id, :to => :library
end

app/controllers/librarians_controller.rb
class LibrariansController < ApplicationController
  before_action :set_librarian, only: [:show, :edit, :update, :destroy]
  # skip_before_action :verify_authenticity_token
  after_action :verify_authorized
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  helper_method :approve_book_request

  # GET /librarians
  # GET /librarians.json
  def index
    # @user = Librarian.find(params[:id])
    # unless current_user.librarian?
    #   unless @user == current_user
    #     redirect_to :back, :alert => "Access denied!"
    #   end
    # end
    # @users = Librarian.all
    # @my_models = policy_Scope(MyModel)
    @librarians = policy_scope(Librarian)
    @librarians = Librarian.all

    @library_dict = {}
    @libs = Library.all

    @libs.each do |l|
      @library_dict[l.id] = l.name
    end

    authorize Librarian
  end

  # GET /librarians/1
  # GET /librarians/1.json
  def show
    # @user = Librarian.find(params[:id])
    # unless current_user.librarian?
    #   unless @user == current_user
    #     redirect_to :back, :alert => "Access denied!"
    #   end
    # end
    # @users = Librarian.all
    #
    @library_dict = {}
    @libs = Library.all

    @libs.each do |l|
      @library_dict[l.id] = l.name
    end

    authorize Librarian
    # @user = User.find(params[:id])
    # unless current_user.librarian?
    #   unless @user == current_user
    #     redirect_to user_homepage, :alert => "Access denied!"
    #   end
    # end

    if(current_user.librarian?)
      @lib = Librarian.find_by_email(current_user.email)
      @lib2 = Librarian.find(params[:id])
      if(@lib.id!=@lib2[:id])
        flash[:alert] = "You are not authorized to perform this action."
        redirect_to(request.referrer || root_path)
      end
    end

  end

  # GET /librarians/new
  def new
    @librarian = Librarian.new
    authorize Librarian
  end

  # GET /librarians/1/edit
  def edit
    authorize Librarian
    if(current_user.librarian?)
      @lib = Librarian.find_by_email(current_user.email)
      @lib2 = Librarian.find(params[:id])
      if(@lib.id!=@lib2[:id])
        flash[:alert] = "You are not authorized to perform this action."
        redirect_to(request.referrer || root_path)
      end
    end
  end

  # POST /librarians
  # POST /librarians.json
  def create
    authorize Librarian
    @librarian = Librarian.new(librarian_params)
    @user = User.new({email:@librarian.email,password:@librarian.password,password_confirmation:@librarian.password})

    # create user entry here
    respond_to do |format|
      if @librarian.save
        @librarian.update(approved:true)
        @user.save
        format.html { redirect_to user_homepage_path, notice: 'Request sent to Admin was authorisation.' }
        format.json { render :show, status: :created, location: user_homepage_path }
      else
        format.html { render :new }
        format.json { render json: @librarian.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /librarians/1
  # PATCH/PUT /librarians/1.json
  def update
    authorize Librarian
    @user = User.find_by_email(@librarian.email)
    respond_to do |format|
      if @librarian.update(librarian_params)
        @user.update({email:@librarian.email})
        format.html { redirect_to librarians_url, notice: 'Librarian was successfully updated.' }
        format.json { render :show, status: :ok, location: @librarian }
      else
        format.html { render :edit }
        format.json { render json: @librarian.errors, status: :unprocessable_entity }
      end
    end
  end

  def list_special_book_request
    authorize Librarian
    query = "select * from book_request"
    #@book_request = BookRequest.find(query)
    @book_request = BookRequest.all.where(is_approved: 'false', hold: 'false')
  end

  def approve_book_request
    authorize Librarian
    @book_request = BookRequest.find(params[:id])
   # query = "update book_request"
    @book_request.update_attribute(:is_approved,"true")

    @book = Book.find(@book_request[:books_id])
    @student = Student.find(@book_request[:students_id])
    @borrow_history = BorrowHistory.new(:date => Date.today, :is_special => @book.special_collection, :books_id => @book.id, :students_id => @student.id, :status => "Approved by Librarian - Book Checked Out")
    @borrow_history.save
      # query_1 = "INSERT INTO borrow_histories (date, is_special, books_id, students_id, status) VALUES
    #                                                    ('#{Date.today}','#{@book.special_collection}','#{@book.id}','#{@student.id}','#{"Checked Out"}')"
    # BorrowHistory.connection.execute(query_1)
  end

  # DELETE /librarians/1
  # DELETE /librarians/1.json
  def destroy
    authorize Librarian
    # @librarian.destroy
    respond_to do |format|
      if @librarian.destroy
        format.html { redirect_to librarians_url, notice: 'Librarian was successfully destroyed.' }
        format.json { head :no_content }
      else
        format.html {redirect_to librarian_url, alert: 'Librarian was not successfully destroyed.'}
      end
    end
  end

  def copy_data
    if self.librarian?


      @user = User.find(self.id)
      if Librarian.find_by_email(self.email).nil?
        @lib = Librarian.new(email: self.email, password: self.encrypted_password, libraries_id: 1)
        @lib.save
        #   flash[:success] = "Successfully saved data to Librarian model"
        # redirect_to librarians_path

        # else
        #   flash[:error] = "Could not create record"
        # end
      end

      # @user = Librarian.find(self.id)
      # if (nil == @user)
      #   @lib = Librarian.create(email: self.email, name:self.email, password: self.encrypted_password, users_id: self.id)
      #   @lib.save
      # else
      #   @lib = Librarian.create(email: self.email, name:self.email, password: self.encrypted_password, users_id: self.id)
      #   @lib.save
      # end
      #
    elsif self.user?
      # @user = User.find(self.id)
      if Student.find_by_email(self.email).nil?
        @stud = Student.new(email: self.email, password: self.encrypted_password)
        @stud.save
        #   flash[:success] = "Successfully saved data to Student model"
        # redirect_to students_path
        # else
        #   flash[:error] = "Could not create record"
        # end
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_librarian
      @librarian = Librarian.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def librarian_params
      params.require(:librarian).permit(:email, :name, :password, :libraries_id)
    end

    def user_not_authorized
      flash[:alert] = "You are not authorized to perform this action."
      redirect_to(request.referrer || root_path)
    end
end

app/helpers/librarians_helper.rb
module LibrariansHelper
end

app/views/librarians/_edit_form.html.erb
<%= form_with(model: librarian, local: true) do |form| %>
  <% if librarian.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(librarian.errors.count, "error") %> prohibited this librarian from being saved:</h2>

      <ul>
        <% librarian.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email , :required => true%>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name , :required => true%>
  </div>

  <div class="field">
    <%= form.label :library_name %><br>
    <%= form.select :libraries_id, options_for_select(Library.all.map{ |l| [l.name, l.id] })%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/librarians/_form.html.erb
<%= form_with(model: librarian, local: true) do |form| %>
  <% if librarian.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(librarian.errors.count, "error") %> prohibited this librarian from being saved:</h2>

      <ul>
      <% librarian.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email , :required => true%>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name , :required => true%>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password, :required => true%>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, :required => true%>
  </div>

  <div>
    <span id="librarian_message"></span>
  </div>

  <div class="field">
    <%= form.label :library_name %><br>
    <%= form.select :libraries_id, options_for_select(Library.all.map{ |l| [l.name, l.id] })%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/librarians/approve_book_request.erb
<script type="text/javascript">
    window.location.href="list_special_book_request"  // put your correct path in a string here
</script>

app/views/librarians/edit.html.erb
<h1>Editing Librarian</h1>

<%= render 'edit_form', librarian: @librarian %>

<%= link_to 'Show', @librarian %> |
<%= link_to 'Back', librarians_path %>

app/views/librarians/index.html.erb
<p id="notice"><%= notice %></p>

<% if current_user.librarian? %>
  <h1>Welcome <%= Librarian.find_by_email(current_user.email).name %> !</h1>
<% else %>
  <h1>Librarians</h1>
<% end %>

<table>
  <thead>
    <% if current_user.admin? %>
      <tr>
        <th>Email</th>
        <th>Name</th>
        <th>Library</th>
        <th colspan="10"></th>
      </tr>
    <% end %>
  </thead>

  <tbody>
    <% @librarians.each do |librarian| %>
      <%# if current_user.librarian? && ((current_user.email == librarian.email) )%>
<!--        <tr>-->
<!--          <td><%#= librarian.email %></td>-->
<!--          <td><%#= librarian.name %></td>-->
<!--          <td><%#= @library_dict[librarian.libraries_id] %></td>-->
<!--          <td><%#= link_to 'Edit', edit_librarian_path(librarian) %></td>-->
<!--          <td><%#= link_to 'Destroy', librarian, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
<!--        </tr>-->

      <% if current_user.admin? %>
        <tr>
          <td><%= librarian.email %></td>
          <td><%= librarian.name %></td>
          <td><%= @library_dict[librarian.libraries_id] %></td>
          <td><%= link_to 'Edit', edit_librarian_path(librarian) %></td>
          <td><%= link_to 'Destroy', librarian, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>

      <% end %>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'View Libraries', libraries_path %><br>
<%= link_to 'View Books', books_path %><br>
<%= link_to 'View Borrowing History', borrow_histories_path %><br>
<%= link_to 'View Special Book Requests', list_special_book_request_path %><br>


<% if current_user.librarian? %>
  <br><%= link_to 'My Profile', Librarian.find_by_email(current_user.email) %><br>
<% end %>

<% unless current_user.librarian? %>
  <br><%= link_to 'Back', user_homepage_path %><br>
<% end %>

app/views/librarians/list_special_book_request.html.erb
<%= @var1 %>

<h1>Books Pending Approval</h1>

<table>
  <thead>
  <tr>
    <th>ID</th>
    <th>Date</th>
    <th>Books_ID</th>
    <th>Book Title</th>
    <th>Book Author</th>
    <th>Student_ID</th>
    <th>Student Name</th>
    <th>Librarians_ID</th>
    <th>Approve</th>
<!--    <th>Deny</th>-->
  </tr>
  </thead>
  <tbody>
  <% @book_request.each do |book_request| %>
      <tr>
        <td><%= book_request.id %></td>
        <td><%= book_request['date'] %></td>
        <td><%= book_request['books_id'] %></td>
        <td><%= Book.find_by_id(book_request['books_id']).title %></td>
        <td><%= Book.find_by_id(book_request['books_id']).author %></td>
        <td><%= Student.find_by_id(book_request['students_id']).id %></td>
        <td><%= Student.find_by_id(book_request['students_id']).name %></td>
        <td><%= book_request['librarians_id'] %></td>
        <td><%= link_to 'Approve', approve_book_request_path(book_request, id: book_request.id)  %></td>
<!--        <td><%#= link_to 'Deny', data: { confirm: 'Are you sure to deny this request?' } %></td>-->
      </tr>
    <% end %>


  </tbody>
    </table>

<%= link_to 'Back', librarians_path %> |

app/views/librarians/new.html.erb
<h1>New Librarian</h1>

<%= render 'form', librarian: @librarian %>

<%= link_to 'Back', librarians_path %>

app/views/librarians/show.html.erb
<p id="notice"><%= notice %></p>

<h2>Librarian Profile</h2><br>

<p>
  <strong>Email:</strong>
  <%= @librarian.email %>
</p>

<p>
  <strong>Name:</strong>
  <%= @librarian.name %>
</p>

<p>
  <strong>Library:</strong>
  <%= @library_dict[@librarian.libraries_id] %>
</p>

<br><%= link_to 'Change Password', edit_user_registration_path %><br>
<%= link_to 'Edit', edit_librarian_path(@librarian) %><br>
<%= link_to 'Back', librarians_path %> |